FROM node:16-alpine

WORKDIR '/app'

# copy package.json to current workdir /app 
# install all dependencies 
COPY package.json .
RUN npm install

#Copy over everything else from our project dir
COPY . .

# Run cmd["npm", "run", "start"] to start up our project 
CMD ["npm", "run", "start"]